### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring21#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA.

In addition to this course, I also teach [DGMD E-28](https://hesweb.dev/e28) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by karnaout** [comment]
Hi all, 
My name is **Khaled** and I'm a **Web and Application Developer** at **Harvard T.H. Chan School of Public Health**. I use WordPress and PHP in my day-to-day work tasks and I've been recently interested in expanding skill-set to include Laravel as it seems to be one of the very solid web frameworks out there. 
I moved to Boston only 7 months ago and I loved the city (minus Winter :D) so much. I worked and studied at **Cornell University** for a year before coming here and prior to that, I was studying B.S. in **Computer Science** at **Monmouth College** in Illinois. 
`Looking forward to work with and learn from all of you!`

**Comment by kristysunnyd** [comment]
Hi everyone! 

I'm Kristy and it's really nice to meet you all. I'm originally from Los Angeles but am currently living in Hong Kong. Some of my hobbies include editing videos, longboarding, and daydreaming (yes, daydreaming haha!). 

The reason I'm taking this course is that I had just taken Susan's DGMD E-2 course in the Fall and would like to further my understanding and skills in utilizing PHP and frameworks. 😄 

I'm really excited to start the course and cannot wait to learn lots this semester.

Kristy

**Comment by adejeffchen** [comment]
Hi all,

I am Jeff Chen. I am a project manager at Apple and lives in California. 

This is my second course from Susan Buck. I enjoyed the previous course DGMD E28 "Single-Page Applications & Interfaces with Vue.js" and thought I will complete the picture with some server side technology. Looking forward to learn some PHP and the Laravel framework. 

During the pandemic, I run 2 miles everyday to have a reason to get out of the house. 

Stay safe.
Jeff

**Comment by kerynegan** [comment]
Hi everyone,

I'm Keryn Egan and I am a candidate for the ALM degree in Digital Media Design. I'm taking this course as part of my final two electives in the program, so after this term I should just have the precapstone and capstone courses remaining! I have the bones of a plan in mind for an application for my capstone project, and I'm hoping to use this class and DGMD E-28 this term to flesh out some understanding and firm up my plans, and also to get some practice in!

Outside of the master's program, I work full-time at Harvard as part of the registrar's office at the Extension School, working on course scheduling and catalog management. In my spare time, I love to work on both illustration and stationery-design projects, and I hope to launch a shop later this year.

Looking forward to the class!
Keryn

**Comment by britney-sandau** [comment]
Hi everyone,

My name is Britney Sandau and I am originally from Idaho. I moved to Massachusetts in August 2019. I had planned to move back to Idaho once I graduate, but I had no idea I would love the New England area so much. The history and architecture draw me in whenever I visit a new town. I am looking forward to the museums opening back up, since I am a history and art buff.

I also love working with computers. Prior to moving to Massachusetts I worked as an IT specialist with a trucking company. Although I like fixing computers, my main passion is computer programming, even though I am still very new at it. The artist in me is excited by all the creative possibilities that can be had by writing code. I honestly don't see an end to what can be created and that fascinates me. It is like a new art form, like music, art or poetry. I have a few ideas of what I would like to create for some websites and apps and I can't wait to learn enough so that I can see my ideas take flight.

I can't wait to get to know you all! B^)

**Comment by karnaout** [comment]
> Hi all,
> 
> I am Jeff Chen. I am a project manager at Apple and lives in California.
> 
> This is my second course from Susan Buck. I enjoyed the previous course DGMD E28 "Single-Page Applications & Interfaces with Vue.js" and thought I will complete the picture with some server side technology. Looking forward to learn some PHP and the Laravel framework.
> 
> During the pandemic, I run 2 miles everyday to have a reason to get out of the house.
> 
> Stay safe.
> Jeff

I always tell myself, starting tomorrow I will run 2 miles a day but never did :D

**Comment by w2KZSmL8** [comment]
Hello everyone,

My name is Bryan.  I'm from the Philippines and am currently in London for college, which I moved to in August 2018.  I got introduced to programming doing social science data analysis, and now I'm taking a few Harvard Extension courses with the aim of broadening my skills in web development and software testing.  I took CSCI E-10, Fundamentals of Web Development before this and I quite enjoyed it.  I'm looking forward to learning more about the server side of web-development.

Also, I'm using Linux (Ubuntu 18.04 LTS, to be exact).  If anyone needs help getting setup, I'm glad to help.  Looking forward to getting to know you all.

**Comment by NEOMorpheus33** [comment]
Hi, I'm Joseph. I started building websites back in 2000. I have a B.S from Ramapo college in businesss/ IT / Philosophy. I'm doin a masters degree here in software engineering. I love to build websites, the challenge, the thrill, the complexity. 

Message me if you want to collaborate or need help. 

my site Joe's App engineering & app education

https://www.joepfanning.com/blog1
(url)) 

Joseph Fanning

**Comment by zrashidharvard2020** [comment]
Hello Everyone, 

This is Zahid from Austin, Texas. I am currently enrolled ALM (Information Management Systems) at HSE. This is my third course towards the degree program. I have been in IT/Software industry  for last 25 years in security arena . My main focus was in Business Development with fortune 500 companies . About six years ago, I have started my own venture . My current operation is in Austin and Bangladesh. Currently I manage group of  developers overseas.

I have a Bachelor's degree in Mathematics from Rowan University, New Jersey and  a Executive MBA from Southern Methodist University , Dallas Texas.  I look forward working with you all .

-Zahid

**Comment by abirray-harvard** [comment]
Hello, everyone!

My name is Abir. I have a Bachelor's Degree in Computer Science and have a major in IT at UVA. I have been a software engineer for the last 20 years developing in JavaScript, C#, Python, and Perl. I expect that I will be able to expand my skills in web development through this course. In my spare time, I like to play squash.

**Comment by scoutperry** [comment]
Hi everybody,

I'm Scout! I am working on a ALM degree in Digital Media Design and enjoyed Susan's DGMD E-2 course so much I decided to keep on going! Under normal circumstances I work at the Harvard Art Museums and also do A/V temp gigs.

 I'm looking forward to learning so much and I am so excited to get started!

**Comment by cgiansante** [comment]
Hi All, 

My name is Curtis Giansante. I am currently working towards an ALM in MIS. I live and work locally as a Web Analytics Developer for a software company. I have been using web technologies in my career for 10 years or so. My love for technology began in grade school when my father brought home an old compaq for me to play with.

Looking forward to helping each other progress through our learnings.

**Comment by susanBuck** [comment]
Thanks everyone for taking the time to introduce yourself. Looking forward to a good semester!
