### ISSUE TITLE
Access Forbidden when trying to access my new Laravel application via Chrome

### ISSUE THREAD

**Issue by kristysunnyd** [susanBuck/e15-spring21#11]
**Environment**
Local Server 

**What operating system are you using?**
Mac

**Describe the problem**
I have followed the steps in the lecture video and notes to start a new Laravel application on my laptop, but am not able to access the application via the local domain. The Error 403 comes up along with this message: 

>**Access forbidden!**
>You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
>
>If you think this is a server error, please contact the webmaster.

**Steps taken**
I have gone through the notes and tried the whole process three times but that's not fixing the issue. I have also tried to look on Google to see try and see if I could fix the error coming up but nothing seems to be working... :( 

**Additional context**
Here is a screenshot from the webpage displaying the error:
<img width="904" alt="Screenshot 2021-02-26 at 1 55 23 AM" src="https://user-images.githubusercontent.com/54469624/109196476-b6e37a00-77d6-11eb-868f-282d0ec8674d.png">

**Comment by susanBuck** [comment]
Hi @kristysunnyd -

Can you share the output of running the command `/Applications/XAMPP/bin/httpd -S` ? This will give us debugging information about your Virtual Hosts config file.

([ref](https://hesweb.dev/e15/notes/local-server/local-domains#debugging-the-virtualhosts-file-ememhttpd-vhostsconfemem))

Also, go ahead and share the full contents of your Virtual Hosts config file so I can double check and also test it on my end.

**Comment by kristysunnyd** [comment]
Hi Susan, 

Thank you! I actually figured it out once I ran the command to find the debugging info. It was a little syntax error within my Virtual Hosts config file causing the issue.. The issue's been resolved now :D
