### ISSUE TITLE
HTTP 500 Error with Bookmark Laravel Project, Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by w2KZSmL8** [susanBuck/e15-spring21#12]
**Environment**
My XAMPP local server.

**What operating system are you using?**
I'm on Linux, Ubuntu 18.04 LTS.

**Describe the problem**
I'm getting an HTTP 500 error when loading the local domain version of the bookmark test project.  I had no problems downloading composer, but when creating the project I got this error message,

```
` $ composer create-project --prefer-dist laravel/laravel bookmark
Creating a "laravel/laravel" project at "./bookmark"
Installing laravel/laravel (v7.30.1)
  - Downloading laravel/laravel (v7.30.1)
  - Installing laravel/laravel (v7.30.1): Extracting archive
Created project in /opt/lampp/htdocs/e15/bookmark
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information

                                                                                   
  [Seld\JsonLint\ParsingException]                                                 
  "https://repo.packagist.org/p2/fakerphp/faker.json" does not contain valid JSON  
  Parse error on line 1:                                                           
                                                                                   
  ^                                                                                
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['          

                                                                                   

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

```

Despite this, the project was created anyway, and I assumed there wouldn't be any further problems.  I have set up the local domain and the virtual host file, both of which point as below:

```
127.0.0.1         e15.bookmark.loc

<VirtualHost *:80>
    ServerName e15bookmark.loc
    DocumentRoot /opt/lampp/htdocs/e15/bookmark/public
    <Directory /opt/lampp/htdocs/e15/bookmark/public>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

```

**Steps taken**
I've re-entered the local domain and virtual host file and restarted my Apache server.  Any help would be appreciated.

**Comment by susanBuck** [comment]
Hi @w2KZSmL8 - I'm booting up my Linux box now to try and recreate. Will follow-up when I have more info.

In the meantime - try looking in `bookmark/storage/logs/laravel.log` for details about the problem.

**Comment by susanBuck** [comment]
Hi again -

Looking closer at the output you shared, it looks like it's downloading an older version of Laravel:

> Installing laravel/laravel (v7.30.1)

It should be at _v8.5.11_.

To dig into this, can you follow the notes here: https://hesweb.loc/e15/notes/laravel/new-laravel-app#composer-installs-an-older-version-of-laravel ?

**Comment by w2KZSmL8** [comment]
Thanks so much, I realised that all this time I had the wrong path set for PHP.  Thanks again.  Also, in case this gets to you, I've updated my access rights for Project 1's repository.

**Comment by susanBuck** [comment]
@w2KZSmL8 - Great, thanks - I'll grade your P1 today.
