### ISSUE TITLE
Thank you for the instructions!

### ISSUE THREAD

**Issue by karnaout** [susanBuck/e15-spring21#14]
Just wanted to drop by and say **thank you** @susanBuck. I really appreciate all the effort you put into creating these very detailed instructions and step-by-step directions. Setting up local servers and mapping them to cloud servers usually terrifies me. When doing so, I very often run into problems and end up spending hours and hours if not days troubleshooting them and this very often leaves me behind or have to work extra hard to catch up with the rest of the class. But in the course, I was able to create multiple local environments and map them to cloud servers, do that on multiple different machines, and yet to run into any roadblocks that weren't documented or talked about in the course documents. (knocking on wood.)  I really appreciate how you made it seem very easy. **Thank you!**

**Comment by susanBuck** [comment]
Thanks for the note, @karnaout! I'm glad the instructions are helpful! :-)
