### ISSUE TITLE
About Project 2 - Validation Success output

### ISSUE THREAD

**Issue by zrashidharvard2020** [susanBuck/e15-spring21#15]
@susanBuck Within the Project 2 requirements outline , I have noticed that if the validation is successful then what type output need to be shown to the user? Do I need to incorporate the database to store the input?

**Comment by susanBuck** [comment]
Hi @zrashidharvard2020 -

Project 2 will not interact with a database (that's something we'll do in Project 3).

If validation is successful, the form processing should complete and the results should be shown to the user. These results will vary depending on what you're building.

For example, in the [bill splitter wireframe](https://s3.amazonaws.com/dwa15.com/wireframe-bill-splitter@2x.png), the results was the output "Everyone owes $18.00"
In the [xkcd password generator](https://s3.amazonaws.com/dwa15.com/wireframe-password-generator@2x.png), the results was the password that was generated.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to re-open or start a new thread if there are any pending questions.
