### ISSUE TITLE
Are we going to have access to the class material after the class is over 

### ISSUE THREAD

**Issue by karnaout** [susanBuck/e15-spring21#16]
Hi there,

I was wondering if we will continue to have access to those lecture videos and notes after we finish the semester? I find myself going back to those notes very often to either grab a CLI command or to maybe watch a segment of a video to refresh my mind on how to do something.

**Comment by susanBuck** [comment]
Hi @karnaout - At the end of the semester, I'll provide students with a .zip archive containing all the course notes and code examples (e.g. my e15 repository). The videos are not included in this archive, but will remain available for 3 months after the semester ends.

**Comment by karnaout** [comment]
Got it. Thank you!!
