### ISSUE TITLE
Project 2 requirement - server side validation

### ISSUE THREAD

**Issue by adejeffchen** [susanBuck/e15-spring21#19]
Hi,

Regarding the following requirement 

> Data from your forms should be validated server-side using Laravel’s validation functionality to avoid unexpected output. To make it easy to check your server-side validation, HTML and JavaScript validation should not be used.

I have 3 input types (input field, dropdown, radio button). **If I only have the input field(s) testable, is that okay?**  (I will still add server side validation for dropdown and radio button inputs but I have pre-select for the dropdown and radio button when the page loads)

Thanks.

**Comment by susanBuck** [comment]
Hi @adejeffchen - Yup, that's fine.

**Comment by adejeffchen** [comment]
Thank you!
