### ISSUE TITLE
Week 2 Part 6 Lecture follow-up: Snippets in VSCode

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring21#2]
In the [Week 2](https://hesweb.dev/e15/week/2), Part 6 video I walk through the process of setting up p1 (Project 1) and during this setup, I use a macro on my computer to fill a HTML file with a starting HTML template.

In the video I said I'd follow-up on this in the forum if you wanted to set up a similar shortcut, so here's the info to do that:

On my system, I do this with a program called [atext](https://www.trankynam.com/atext).

Alternatively, if you're using VSCode (another topic covered in this week's materials) you can create similar shortcuts using [Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets).

If you dig into either of these techniques and have any questions, let me know.

**Comment by karnaout** [comment]
I believe VS Code now has Emmet built in so you can just type `doc` and then hit the enter or tab key to get some HTML boilerplate content. I think the shortcut might be a little different depending on the version you're using or maybe a few other elements but you can look them up [very quickly here](https://docs.emmet.io/cheat-sheet/)

<img width="561" alt="Screen Shot 2021-02-07 at 8 58 00 AM" src="https://user-images.githubusercontent.com/13064007/107148701-a56b2880-6922-11eb-98d4-bbac9ee483b7.png">

<img width="759" alt="Screen Shot 2021-02-07 at 8 58 15 AM" src="https://user-images.githubusercontent.com/13064007/107148703-a603bf00-6922-11eb-8fa2-bc6dab0abb8a.png">

**Comment by susanBuck** [comment]
Thanks for sharing @karnaout!

**Comment by kerynegan** [comment]
> I believe VS Code now has Emmet built in so you can just type `doc` and then hit the enter or tab key to get some HTML boilerplate content. I think the shortcut might be a little different depending on the version you're using or maybe a few other elements but you can look them up [very quickly here](https://docs.emmet.io/cheat-sheet/)

Cool! Thanks, @karnaout!
