### ISSUE TITLE
Bookmark search setup returns "Undefined variable:"  "$searchTerms"

### ISSUE THREAD

**Issue by scoutperry** [susanBuck/e15-spring21#20]
https://github.com/scoutperry/e15/tree/main/bookmark

Ok so maybe I messed up following the notes first instead of the lecture (so I didn't troubleshoot as I went) but I have also watched the lecture and I can't see how $searchTerms isn't being defined for the view. It won't load the welcome page at all. I'm sure this is something small but I tried to see if the variables matched and they seem to... maybe there is an issue with the Page controller but I can't see it. I even did the suggestion to add the ?? to the $searchTerms variable and it threw a syntax error in the same line for an unexpected ')' that I also couldn't really understand.

<img width="1360" alt="Screen Shot 2021-03-17 at 8 54 32 PM" src="https://user-images.githubusercontent.com/52388305/111559157-66709400-8766-11eb-8113-51c3b1b2ef47.png">
<img width="1335" alt="Screen Shot 2021-03-17 at 8 54 39 PM" src="https://user-images.githubusercontent.com/52388305/111559174-6e303880-8766-11eb-9ccd-899a98212c2a.png">

**Comment by susanBuck** [comment]
Hi @scoutperry - FYI cloning your code now to debug; will follow-up shortly with what I find.

**Comment by susanBuck** [comment]
Currently, your homepage (`/`) is triggering the _index_ method in the _PageController_:

```php
Route::get('/', [PageController::class, 'index']);
```

This method is returning your welcome view, but it's not passing any variables/data to it, which is why you're getting the _Undefined variable: searchTerms_ error:

```php
/**
     * GET /
     */
    public function index()
    {
        return view('pages/welcome');
    }
```

I believe you want the `/` route to trigger the _welcome_ method instead, as that is set up to pass the variables:

```php
/**
     * GET /
    * Display the application welcome page with a search feature
    */
    public function welcome()
    {
        # If there is data stored in the session as the results of doing a search
        # that data will be extracted from the session and passed to the view
        # to display the results
        return view('pages/welcome')->with([
            'searchTerms' => session('searchTerms', null),
            'searchType' => session('searchType', null),
            'searchResults' => session('searchResults', null)
        ]);
    }
```

Give that a shot and let me know if you have follow-up questions.

**Comment by scoutperry** [comment]
I am relieved to say that not only was that effective, I also understand **why** that was effective. Thank you!!!!

**Comment by susanBuck** [comment]
:-)
