### ISSUE TITLE
Blade auto-formatting (View file)

### ISSUE THREAD

**Issue by kristysunnyd** [susanBuck/e15-spring21#21]
Hi 😄 

For some reason, my VSCode auto-formatting started merging all the `@if` and `@elseif` lines into one line... Is there any way to avoid this? I've tried to Google whether this is an issue with perhaps the extension, but I haven't been able to figure it out. Is anyone else experiencing this issue? 

It's not a huge deal, because it stops when I turn off the auto-formatting but it would be great if anyone had any solutions. ⭐️

**Comment by kristysunnyd** [comment]
After formatting the text with some HTML it's helping a little, as it's splitting them into separate lines again. But the auto-formatting is still making it look a little weird. 🥺

**Comment by susanBuck** [comment]
Hi @kristysunnyd - That sounds frustrating! Can you give me an example of which file in your repo this is happening on? I'd like to test it on my end to see if I can recreate.

**Comment by kristysunnyd** [comment]
Hi @susanBuck - It's happening on the main child view file for my project. I've named it app.blade.php in my repo.

**Comment by susanBuck** [comment]
Hi @kristysunnyd - I was able to recreate the issue you're describing on my end. I narrowed it down to the use of a `<` character in the _if_ statement's boolean expression. Here's a simplified example:

Here we use a `>` (greater than) character and it will auto-format correctly:
```php
@if (1 > 5)
A
@elseif (true)
B
@endif
```

Here we use a `<` (less than) character and it will _not_ auto-format correctly, bunching everything on one line:
```php
@if (1 < 5) A @elseif (true) B @endif @endsection
```

I'd categorize this as a bug in the blade formatting extension, so I filed an issue alerting them to the problem:
https://github.com/amirmarmul/laravel-blade-vscode/issues/9

As a work around, you can accomplish the same thing you're looking for here without conditionals by using the [Str::plural helper](https://laravel.com/docs/8.x/helpers#method-str-plural)

Before:
```php
{{-- This @if block is meant to makeup for the different scenarios of hour(s) and minute(s) --}}
@if($hours < 1)
{{$minutes}} minutes
@elseif($hours <=1 & $minutes <=1)
{{$hours}} hour & {{$minutes}} minute
@elseif($hours <=1 & $minutes> 1)
{{$hours}} hour & {{$minutes}} minutes
@elseif($hours > 1 & $minutes <= 1)
{{$hours}} hours & {{$minutes}} minute
@else 
{{$hours}} hours & {{$minutes}} minutes
@endif
```


After:
```php
{{ Str::plural('hour', $hour) }} & {{ Str::plural('minute', $minutes) }}
```

**Comment by kristysunnyd** [comment]
Hi @susanBuck - Thank you very much for the help and finding the issue! The formatting was giving me a nightmare.. 😞  but I'm glad to understand the issue. I think I'll implement the **Str::plural** helper since it'll streamline my code. 😄 Thank you again!
