### ISSUE TITLE
Access Denied Error when publishing my app

### ISSUE THREAD

**Issue by cgiansante** [susanBuck/e15-spring21#23]
[**Repository URL**](https://github.com/cgiansante/e15/tree/main/p2)
[**Production URL**](http://e15p2.curtisg.me)

**Describe the problem**
Application was working as expected on localhost. After pulling from GitHub to my production server, I am getting a permission error when accessing my http://e15p2.curtisg.me from a browser. I have updated my domain's DNS records (new droplet), updated new droplet's /etc/apache2/sites-enabled/000-default.conf file, update the permissions for storage & bootstrap/cache,  and cleared local machine DNS cache. 

**To Reproduce**
1. Go to e15p2.curtisg.me
2. Screenshot of the error is below,
![Screen Shot 2021-03-25 at 11 48 41 PM](https://user-images.githubusercontent.com/24394927/112574444-a36f0300-8dc4-11eb-96eb-de68e899d9bc.png)

**Additional context**
Copy of /etc/apache2/sites-enabled/000-default.conf
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        <Directory /var/www/html/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

</VirtualHost>

<VirtualHost *:80>
    ServerName e15p2.curtisg.me
    DocumentRoot "/var/www/html/e15/p2"
    <Directory "/var/www/html/e15/p2/">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

Any help is appreciated. Thank you!

**Comment by susanBuck** [comment]
Hi @cgiansante -

On your production server can you run the command `apachectl -S` and share the output? This will potentially flag any issues that might exist in your VirtualHost settings.

**Comment by susanBuck** [comment]
Other notes:

Because you're setting up a Laravel-based application, the document root/directory of your virtual host should point to the _public_ subdirectory within your project.

```
<VirtualHost *:80>
    ServerName e15p2.curtisg.me
    DocumentRoot "/var/www/html/e15/p2/public"
    <Directory "/var/www/html/e15/p2/public">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by cgiansante** [comment]
Thank you, I can't believe I missed that. That helped with the permission issue, but now nothing is loading in Safari and I'm seeing a different error in Chrome.

![Screen Shot 2021-03-26 at 12 08 58 AM](https://user-images.githubusercontent.com/24394927/112575826-7839e300-8dc7-11eb-8cc9-67adb2378da0.png)

Here is the result of apachectl -S, 

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:2)
         port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:2)
         port 80 namevhost e15p2.curtisg.me (/etc/apache2/sites-enabled/000-default.conf:21)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
Mutex default: dir="/var/run/apache2/" mechanism=default 
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33
root@hes4:/var/www/html/e15/p2#

**Comment by susanBuck** [comment]
The 500 server error likely indicates there's some error with the application.

Try going through the troubleshooting notes here: 
https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#troubleshooting

**Comment by cgiansante** [comment]
The problem was with my app key. Unfortunately, I rebuilt the application and did another commit after the p2 deadline.This did not change the code that I had developed. I was having composer issues on my production server so my initial attempts at troubleshooting were unsuccessful.

Thank you!
