### ISSUE TITLE
Typing Practice for Programmers: https://typing.io

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring21#27]
Hi everyone,

The app [typing.io](https://typing.io) came across my radar from a student in my other course, and I wanted to share it here because I thought it was interesting. 

> What is typing.io? Typing.io is a typing tutor/trainer for programmers. Typing.io's lessons are based on open source code, allow you to practice typing the key sequences that appear in real code.

> Does typing speed bottleneck programming? Yes, every typo interrupts the thought process not unlike a slow compiler or UI lag. Faster and more accurate typing is like a better REPL — not only does this speed up development, it fundamentally affects the exploration process.

Hope everyone has a nice week.

**Comment by kerynegan** [comment]
Oof. I did not do nearly as well as I'd have hoped. [Mavis Beacon](https://en.wikipedia.org/wiki/Mavis_Beacon_Teaches_Typing) would be incredibly disappointed in me.

**Comment by britney-sandau** [comment]
My goodness, this is so very helpful!
