### ISSUE TITLE
Week 9 assignment due date/time

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e15-spring21#29]
Hi Susan,

It looks like the Week 9 assignment had a due date of April 8 at 4 pm, not by 11:59 pm. I noticed that it marked me late for submitting just after 9 pm. Was this a mistake, or did I miss that this week an exception to the usual time?

![image](https://user-images.githubusercontent.com/35839424/114283605-908d3d00-9a18-11eb-9b4d-54b97ca270f8.png)

Thanks!
Keryn

**Comment by susanBuck** [comment]
Should be the usual deadline. I'll correct this when I get back to my computer. Thanks for the heads up.

**Comment by susanBuck** [comment]
Just corrected to 11:59pm and confirmed it's no longer showing late for you. 👍
