### ISSUE TITLE
This week's assignment is NOT posted yet? 

### ISSUE THREAD

**Issue by karnaout** [susanBuck/e15-spring21#31]
Has this week's assignment been posted yet or am I having some caching issues?
![image](https://user-images.githubusercontent.com/13064007/116007432-be0fe400-a5dd-11eb-98e5-3c4421dd5220.png)

**Last checked Sunday, Apr 25 at 3:50 pm**.

**Comment by adejeffchen** [comment]
It is live on Canvas.

**Comment by karnaout** [comment]
I mean the assignment preview. I usually skim through that before starting the quiz on Canvas.

**Comment by susanBuck** [comment]
Apologies for that - forgot to activate the links. Fixed now.
