### ISSUE TITLE
Unexpected Redirects

### ISSUE THREAD

**Issue by sneadthaman** [susanBuck/e15-spring21#35]
**Repository URL**
https://github.com/sneadthaman/e15/tree/main/p3

**Production URL**

**Describe the problem**
Some of the routes are working as expected ('/' , '/{slug}') but other routes in the same auth group are being redirected back to '/'. I've looked for clues on this Stack forum (https://stackoverflow.com/questions/35020477/laravel-unexpected-redirects-302#45356645) but can't figure this out. 

**To Reproduce**
1. Go to project homepage ('/' and login as either Jill or Jamal)
2. Click on Projects link in the navigation

**Additional context**
I have 3 projects seeded in the db so there is definitely data that the route could use

**Comment by susanBuck** [comment]
Hi @sneadthaman - I'm not seeing links to login - am I missing something? : )

**Comment by sneadthaman** [comment]
If you run the app locally, the login screen appears automatically for non-logged in users
![image](https://user-images.githubusercontent.com/30006142/117846253-41bd0800-b24f-11eb-89a9-67abd2b004a0.png)

use pw: asdfasdf

**Comment by susanBuck** [comment]
Ah ok, I was looking at your production site. I will clone locally to test now.

**Comment by susanBuck** [comment]
The `/{slug}` route is ambiguous with the `/projects` route. 

So what is happening when your visit `/projects` is it's triggering `DashboardController::class, 'show'` which upon not finding a customer slug, is redirecting back to `/`:

To address this, rearrange your routes so `/projects` is first and takes precedence over `/{slug}`.

**Comment by sneadthaman** [comment]
Working!! Thank you so much
