### ISSUE TITLE
Website recommendations to stay current with changes in technology.

### ISSUE THREAD

**Issue by britney-sandau** [susanBuck/e15-spring21#4]
This is a bit off topic and mainly for my curiosity. I am a newbie in the field of computer science and was wondering if anyone has any recommendations for websites, magazines, or journals that I could read, that would help me stay current with the ever changing world of computers. 

For example, I stumbled upon a YouTube video that advertised a once trusted software program had been bought by a nefarious company and now the latest version had become a form of malware. Another example is the w3techs.com website in one of last week's videos, where the Prof. discussed the latest server trends. How does one keep up with all of the different changes and trends? Is there something similar to the "Wall Street Journal" but for computers? 

Thank you for any recommendations anyone can provide.

**Comment by susanBuck** [comment]
Here are some newsletters I subscribe to:
+ https://programmingdigest.net 
+ https://laravel-news.com
+ https://css-tricks.com (for front-end news)

Medium often has good content - you can browse by category, e.g. https://medium.com/topic/programming

Curious to hear some resources/newsletters everyone else subscribes to.

**Comment by britney-sandau** [comment]
Thank you so very much for these recommendations! They will help provide me with a great starting point.
