### ISSUE TITLE
Issue with cloning E15 repository

### ISSUE THREAD

**Issue by w2KZSmL8** [susanBuck/e15-spring21#5]
Hello there,

Just an issue I've been having, but when I try to clone the git used for our LAMP-stack Droplet using the provided command, the link to which is [here](https://hesweb.dev/e15/notes/production-server/setup#clone-your-repository).

` $ git clone git@github.com{username}/e15.git`

I get the following error message about the repository not existing:

> Please make sure you have the correct access rights
and the repository exists.
root@hes15:/var/www/html# git clone git@github.com:w2KZSmL8/e15.git
Cloning into 'e15'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

My SSH key has been authenticated, so I'm sure it isn't access rights.  I apologise if I'm missing something here about where to get the repository, but does anyone know how to get it?  Thanks so much for the assistance.

Edit:

I've attached below a picture of all the repositories I have access to, in case this helps.
![Screenshot from 2021-02-12 05 31 55@2x](https://user-images.githubusercontent.com/47384476/107733739-a79eff80-6cf3-11eb-9327-336008e31487.png)

Sincerely,
Bryan

**Comment by susanBuck** [comment]
Hi @w2KZSmL8 -

I don't see a *e15* repository in the screenshot you shared, nor one in the list here: https://github.com/w2KZSmL8?tab=repositories

That should have been created as part of the steps outlined here: https://hesweb.dev/e15/notes/git/repository-setup

Can you let me know where you are in the steps of having the repo set up on Github, cloned to your computer, etc?

**Comment by w2KZSmL8** [comment]
Hello there,

Thanks so much for linking the pertinent part of the notes.  It turns out I created a different Github account for that purpose without realising it.  I've fixed the errors.

Thanks again,
Bryan

**Comment by susanBuck** [comment]
@w2KZSmL8 - Glad you got it sorted out. : )
