### ISSUE TITLE
Bonus/optional material: hesweb utils

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring21#8]
Hi everyone,

When I had you create your course repositories, I had you use a template I provided ([susanBuck/eX](https://github.com/susanBuck/eX)). In this template, I included a bash script called *utils* that provides shortcuts for many of the sys-admin related tasks we have to do when managing our servers.

If interested, [here is a video explaining how to use these utils...](https://www.youtube.com/embed/VACUFUjEUho?rel=0&showinfo=0)

[And the accompanying notes can be found here...](https://hesweb.dev/e15/notes/misc/utils)

As I indicate in the video and notes, this script is considered in "beta" so I welcome any feedback or notes on issues you face when using it. It's also not required that you dig into this material or use the script - just throwing it out there for those that are interested!

**Comment by zrashidharvard2020** [comment]
Thanks for the video. I just watched it . Very helpful setting up the environment.

**Comment by scoutperry** [comment]
for some reason choosing the 'a' option to update it would produce this the next time I tried to access it...
```
MacBook-Pro-2:e15 $ bash utils
utils: line 1: syntax error near unexpected token `newline'
utils: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```
I replaced the file, but now I'm afraid to try to update it...

**Comment by susanBuck** [comment]
@scoutperry - Thanks for testing it out. 

I've seen that issue happen when I had a bad path in the URL it uses to grab the latest copy. It's possible you had used my template when that bug was still present.

Can you try updating again? Worse case scenario, it happens again and you have to manually replace it again. : )

**Comment by scoutperry** [comment]
huh, looks like its fine now. Thanks!
