### ISSUE TITLE
visual studio automatic bracket closer

### ISSUE THREAD

**Issue by caronee** [susanBuck/e15-spring21#9]
Hello

Is there a setting in visual studio or an extension that will automatically input a closing bracket/ parentheses/ ']'/ '}'/ '>' if we put the open version? I am used to it from my other coding ime coming from python and i'd like to know if there's a similar option!

**Comment by susanBuck** [comment]
If you enable **HTML: Auto Closing Tags** in settings, it will auto-close HTML tags when working in a .html file.

![image](https://user-images.githubusercontent.com/237711/108416334-8b6ff680-71fc-11eb-88bd-7e6f15200a89.png)

If working in a .php file that uses HTML code (e.g. a view file), you need to change the file mode to be HTML in order for that to work. The file mode can be changed from the bottom right bar on the interface - [screenshot](https://youtu.be/c57HqJNCOvQ
)) 

When working in straight-php files, I am noticing it auto-closes things like curly brackets and quotes.

For example, if I start typing a function definition (`function example() {`), right after I type the open curly bracket, it injects a closing curly bracket.

Same thing for quotes - if I type something like `echo '` it immediately adds a closing quote.

If it's not doing that for you, check the following settings are enabled:

![image](https://user-images.githubusercontent.com/237711/108416289-7e530780-71fc-11eb-9983-40d41a0b6fa6.png)

**Comment by susanBuck** [comment]
Going to close out this thread, but feel free to re-open @caronee if you still have questions about this/it's not doing exactly what you'd like.
